### ISSUE TITLE
Highlighted line color would look better darker

### ISSUE THREAD

**Issue by coffenbacher** [jaredgorski/Styrokai#2]
![image](https://user-images.githubusercontent.com/245867/52283795-2b69c880-2931-11e9-8dd9-e6e379481970.png)

I think a darker gray here, closer to black, would work a lot better as all the font colors are chosen to look good on black.

https://www.reddit.com/r/vscode/comments/an7pnc/styrokai_pure_black_and_contrasty_with/efsam1p/

**Comment by jaredgorski** [comment]
Thanks @coffenbacher! Updated to `#333333` this morning. Hope this works better; let me know if not. Always feel free to send a PR.

Closed by https://github.com/jaredgorski/Styrokai/commit/2c851648e551eba6096fcb1bf2ded34b3a62edd7

**Comment by coffenbacher** [comment]
Much better! Thanks!
