### ISSUE TITLE
Publish extension to Open VSX Registry

### ISSUE THREAD

**Issue by ebramirez** [jaredgorski/Styrokai#6]
**Is your feature request related to a problem? Please describe.**
Other IDEs based on Eclipse Theia (The engine behind VS Code) like VSCodium, Eclipse Che, GitPod, etc, use [Open VSX Registry](https://open-vsx.org) instead of the proprietary VS Code Marketplace, so this plugin is not available for those using them.

**Describe the solution you'd like**
I would like that the plugin is deployed to the Open VSX Registry upon release, like it is currently done for the VS Code Marketplace.

The procedure is documented [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by jaredgorski** [comment]
Hi! Since I don't use VSCode at all and haven't for a long long time, I'm not maintaining my old VSCode themes. Perhaps I should archive this repo.

If you'd like, you can fork this repo and do whatever you want to do with it 😸
